/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndkreport_NdkJniUtils */

#ifndef _Included_com_ndkreport_NdkJniUtils
#define _Included_com_ndkreport_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndkreport_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndkreport_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     com_ndkreport_NdkJniUtils
 * Method:    setCLanguageString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndkreport_NdkJniUtils_setCLanguageString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
